import { v4 as uuid } from "uuid";
import {Iphone13miniImage,
  Iphone13Image,Iphone13ProImage,IphoneSEImage,SamsungS21UltraImage,
  SamsungGalaxyZFoldImage,SamsungGalaxyM21Image,SamsungGalaxyM52Image,
  Oneplus10ProImage,Oneplus9ProImage,OneplusNordImage,OneplusNord2Image,
  Googlepixel6ProImage,Googlepixel6Image,Googlepixel4Image,Googlepixel3aImage,
  Nokia105Image,Nokia150Image,Nokia5310Image} from "../../assets";
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    productName: "iPhone 13 Pro",
    brand:"Iphone",
    RAM: "6GB",
    price: "130000",
    rating:"4.9",
    reviews:"786",
    tag:"new",
    inStock: true,
    displayImg:Iphone13ProImage,
    categoryName: "iPhone"
  },
  {
    _id: uuid(),
    productName: "iPhone 13",
    brand:"Iphone",
    RAM: "4GB",
    price: "85000",
    rating:"4.5",
    reviews:"889",
    tag:"new",
    inStock: false,
    displayImg:Iphone13Image,
    categoryName: "iPhone"
  },
  {
    _id: uuid(),
    productName: "iPhone 13 mini",
    brand:"Iphone",
    RAM: "4GB",
    price: "65000",
    rating:"4.1",
    reviews:"577",
    tag:"old",
    inStock: true,
    displayImg:Iphone13miniImage,
    categoryName: "iPhone"
  },
  {
    _id: uuid(),
    productName: "iPhone SE",
    brand:"Iphone",
    RAM: "2GB",
    price: "48000",
    rating:"3.5",
    reviews:"124",
    tag:"old",
    inStock: true,
    displayImg:IphoneSEImage,
    categoryName: "iPhone"
  },
  {
    _id: uuid(),
    productName: "Samsung S21 Ultra",
    brand:"Samsung",
    RAM: "12GB",
    price: "95000",
    rating:"4.8",
    reviews:"610",
    tag:"new",
    inStock: false,
    displayImg:SamsungS21UltraImage,
    categoryName: "Android"
  },
  {
    _id: uuid(),
    productName: "Samsung Z fold3",
    brand:"Samsung",
    RAM: "12GB",
    price: "149000",
    rating:"4.7",
    reviews:"334",
    tag:"new",
    inStock: true,
    displayImg:SamsungGalaxyZFoldImage,
    categoryName: "Android"
  },
  {
    _id: uuid(),
    productName: "Samsung Galaxy M21",
    brand:"Samsung",
    RAM: "4GB",
    price: "12999",
    rating:"2.9",
    reviews:"952",
    tag:"new",
    inStock: true,
    displayImg:SamsungGalaxyM21Image,
    categoryName: "Android"
  },
  {
    _id: uuid(),
    productName: "Samsung Galaxy M52",
    brand:"Samsung",
    RAM: "6GB",
    price: "24999",
    rating:"4.1",
    reviews:"957",
    tag:"new",
    inStock: true,
    displayImg:SamsungGalaxyM52Image,
    categoryName: "Android"
  },
  {
    _id: uuid(),
    productName: "Oneplus 10 Pro",
    brand:"Oneplus",
    RAM: "12GB",
    price: "65999",
    rating:"4.8",
    reviews:"543",
    tag:"new",
    inStock: false,
    displayImg:Oneplus10ProImage,
    categoryName: "Android"
  },
  {
    _id: uuid(),
    productName: "Oneplus 9 Pro",
    brand:"Oneplus",
    RAM: "12GB",
    price: "58999",
    rating:"4.5",
    reviews:"878",
    tag:"old",
    inStock: true,
    displayImg:Oneplus9ProImage,
    categoryName: "Android"
  },
  {
    _id: uuid(),
    productName: "Oneplus Nord 1",
    brand:"Oneplus",
    RAM: "8GB",
    price: "22799",
    rating:"2.9",
    reviews:"921",
    tag:"old",
    inStock: true,
    displayImg:OneplusNordImage,
    categoryName: "Android"
  },
  {
    _id: uuid(),
    productName: "Oneplus Nord 2",
    brand:"Oneplus",
    RAM: "8GB",
    price: "24799",
    rating:"3.6",
    reviews:"765",
    tag:"new",
    inStock: true,
    displayImg:OneplusNord2Image,
    categoryName: "Android"
  },
  {
    _id: uuid(),
    productName: "Pixel 6 Pro",
    brand:"Google",
    RAM: "12GB",
    price: "90999",
    rating:"4.5",
    reviews:"198",
    tag:"new",
    inStock: false,
    displayImg:Googlepixel6ProImage,
    categoryName: "Android",
  },
  {
    _id: uuid(),
    productName: "Pixel 6",
    brand:"Google",
    RAM: "8GB",
    price: "65000",
    rating:"4.2",
    reviews:"275",
    tag:"new",
    inStock: true,
    displayImg:Googlepixel6Image,
    categoryName: "Android",
  },
  {
    _id: uuid(),
    productName: "Pixel4",
    brand:"Google",
    RAM: "6GB",
    price: "37990",
    rating:"3.8",
    reviews:"216",
    tag:"old",
    inStock: true,
    displayImg:Googlepixel4Image,
    categoryName: "Android",
  },
  {
    _id: uuid(),
    productName: "Pixel 3a",
    brand:"Google",
    RAM: "4GB",
    price: "24090",
    rating:"3.4",
    reviews:"129",
    tag:"old",
    inStock: false,
    displayImg:Googlepixel3aImage,
    categoryName: "Android",
  },
  {
    _id: uuid(),
    productName: "Nokia 105",
    brand:"Nokia",
    RAM: "1GB",
    price: "1339",
    rating:"4.0",
    reviews:"995",
    tag:"new",
    inStock: true,
    displayImg:Nokia105Image,
    categoryName: "keypad",
  },
  {
    _id: uuid(),
    productName: "Nokia 5310",
    brand:"Nokia",
    RAM: "1GB",
    price: "3545",
    rating:"4.0",
    reviews:"767",
    tag:"old",
    inStock: true,
    displayImg:Nokia150Image,
    categoryName: "keypad",
  },
  {
    _id: uuid(),
    productName: "Nokia 150",
    brand:"Nokia",
    RAM: "1GB",
    price: "2520",
    rating:"4.0",
    reviews:"898",
    tag:"new",
    inStock: false,
    displayImg:Nokia5310Image,
    categoryName: "keypad"
  }
];
